name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run flake8 (lint)
        run: poetry run flake8 .

      - name: Clear mypy cache
        run: rm -rf .mypy_cache

      - name: Run mypy (type checks)
        run: poetry run mypy order_system user product

      - name: Run tests
        run: poetry run pytest -v
